### ISSUE TITLE
Discussion on tech stack

### ISSUE THREAD

**Issue by noobling** [codersforcauses/home2health#1]
Share your thoughts about what tech stack we should use.

Here are my thoughts

> These are libraries and frameworks that you will be using. I have carefully selected these tools with the following criteria in mind.
> 
> Ease of use
> Usefulness
> Relevance in the industry
> Community/ecosystem supporting it
> Flexibility
> Here is the list
> 
> JavaScript, HTML, CSS (Fundamental building blocks of the internet. All websites are built upon this)
> React (Frontend framework to help build web applications)
> Cypress + Jest (Testing your code is just as important as writing it)
> Materialize CSS (We are not designers we need some good looking UI components)

On top of that, we need a backend to persist data. Options from easy to hard are Node JS/(express, koa, hapi, fastly) -> prisma/graphql -> Laravel/Django/Rails

The database can be SQL or NoSQL if you use graphql likely we will want NoSQL

**Comment by innocentmm** [comment]
We're going to use React.
Have to convert what's been done on the page so far to React.

**Comment by innocentmm** [comment]
Express/ NodeJS for the backend.

**Comment by innocentmm** [comment]
MongoDB for the database.
