### ISSUE TITLE
Blog Authors are ID

### ISSUE THREAD

**Issue by frinzekt** [codersforcauses/home2health#102]
![image](https://user-images.githubusercontent.com/44391389/75600645-b6919f80-5aec-11ea-8819-764daa3445db.png)

Payload being Delivered (Source of Issue):

![image](https://user-images.githubusercontent.com/44391389/75600654-cf9a5080-5aec-11ea-8f81-2df1989e4d3b.png)

**Comment by JKKim98** [comment]
Fixed by #108
