### ISSUE TITLE
User profile page backend

### ISSUE THREAD

**Issue by JKKim98** [codersforcauses/home2health#52]
Get user's
- Profile details, summary, and picture
- Get user's posts
- Get user's comments

**Comment by innocentmm** [comment]
Oooo let me know when this is completed, it'll make what I'm trying to do with auth easier

**Comment by JKKim98** [comment]
@innocentmm well it's not even started, let alone assigned... if you're already doing it as part of auth then assign yourself eh

**Comment by shazzatherazza** [comment]
Merged into master.
