### ISSUE TITLE
Comments on Post with CRUD operations

### ISSUE THREAD

**Issue by noobling** [codersforcauses/home2health#6]
Posts are not yet complete but you can still build out this whole feature. Make sure to create new files and components to do this to ensure minimal conflicts. Up to you how to ui looks.

## Acceptance criteria
A user can
* view comments
* create a comment
* delete a comment
* update a comment

What is not required first pass
* users can only delete their own comment (we don't have auth yet)
* comments linking to users or posts (neither features are complete

**Comment by shazzatherazza** [comment]
The backend routes have been completed for this, so now the UI needs to be done.

**Comment by JKKim98** [comment]
Thanks @shazzatherazza and every one for the awesome work!
