### ISSUE TITLE
User login and register 

### ISSUE THREAD

**Issue by noobling** [codersforcauses/home2health#7]
## Acceptance Criteria
- [x] Page to login
- [x] Page to register
- [x] Can login and register with correct credentials
- [x] Displays appropriate error messages when validation fails e.g. incorrect credentials and missing form fields

**Comment by JKKim98** [comment]
Registration form needs to be similar to http://pielink.net/register/ as foretold in [Draft Webpage Landing and Tabs sv26.5.19.docx](https://github.com/codersforcauses/home2health/raw/master/Draft%20Webpage%20Landing%20and%20Tabs%20sv26.5.19.docx)

**Comment by innocentmm** [comment]
Hey @hvislyset what part of this are you working on? @JKKim98 and I are working on the UI, and then integrating https://www.auth0.com into it for authorisation of log ins. We're finally going to want to connect the database with the UI, i.e. point the inputs to the data base. You can work on whatever part you'd like, just let us know so we don't duplicate work.

**Comment by hvislyset** [comment]
Hey @innocentmm was hoping to work on the server side validation of user logins and registrations. So using auth0 and integrating it with the database etc.

**Comment by innocentmm** [comment]
Okay awesome @hvislyset I'll get the UI done and you can handle the data base and auth0 side of things?

**Comment by hvislyset** [comment]
I'll get on to that.

**Comment by Hanchooi** [comment]
There's no space for user to key in email address at sign up page yet.

Signing up with just Name, User Name and Password will cause page to show "Validation errors:
The email already exists in our database. "

**Comment by shazzatherazza** [comment]
Is this alright to close?

**Comment by JKKim98** [comment]
@shazzatherazza Yeah it is. Thank you and every one for the good work!
