### ISSUE TITLE
User profile page

### ISSUE THREAD

**Issue by noobling** [codersforcauses/home2health#8]
Work with #7 to determine user schema

## Acceptance Criteria
- [ ] Displays all relevant user information in a clean way
- [ ] Does not display any sensitive

**Comment by JKKim98** [comment]
@noobling @innocentmm is there a particular design or layout the clients want or are we free styling?

**Comment by noobling** [comment]
Refer to the doc in the repo provides some colours to use

**Comment by JKKim98** [comment]
closed with #32 and #55
